import { StyleSheet } from "react-native";

export const createStyles = () =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "flex-end",
    },
    container: {
      flex: 1,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      maxHeight: "92%",
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: "600",
      flex: 1,
      textAlign: "center",
    },
    closeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
    },
    scrollView: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 20,
    },
    inputGroup: {
      marginBottom: 20,
    },
    label: {
      fontSize: 16,
      fontWeight: "500",
      marginBottom: 6,
    },
    labelWithAction: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 6,
      minHeight: 20,
    },
    plusIcon: {
      width: 20,
      height: 20,
      borderRadius: 10,
      justifyContent: "center",
      alignItems: "center",
    },
    rowContainer: {
      flexDirection: "row",
      marginBottom: 20,
    },
    halfWidth: {
      flex: 1,
    },
    textInput: {
      height: 38,
      minHeight: 38,
      borderWidth: 1,
      borderRadius: 10,
      paddingHorizontal: 12,
      fontSize: 16,
      textAlign: "left",
      textAlignVertical: "center",
    },
    selectButton: {
      height: 38,
      minHeight: 38,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: 1,
      borderRadius: 10,
      paddingHorizontal: 12,
    },
    selectButtonText: {
      fontSize: 16,
      flex: 1,
    },
    cardNumberContainer: {
      height: 38,
      minHeight: 38,
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderRadius: 10,
      paddingHorizontal: 12,
    },
    cardNumberPrefix: {
      fontSize: 16,
      marginRight: 4,
      fontWeight: "500",
      textAlignVertical: "center",
    },
    cardNumberInput: {
      flex: 1,
      fontSize: 16,
      textAlign: "left",
      textAlignVertical: "center",
      height: "100%",
      paddingVertical: 0,
    },
    amountContainer: {
      height: 38,
      minHeight: 38,
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderRadius: 10,
      paddingHorizontal: 12,
    },
    currencySymbol: {
      fontSize: 16,
      marginRight: 8,
      fontWeight: "500",
    },
    amountInput: {
      flex: 1,
      fontSize: 16,
      textAlign: "left",
      textAlignVertical: "center",
      height: "100%",
      paddingVertical: 0,
    },
    dateButton: {
      height: 38,
      minHeight: 38,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: 1,
      borderRadius: 10,
      paddingHorizontal: 12,
    },
    dateText: {
      fontSize: 16,
    },
    errorText: {
      fontSize: 14,
      marginTop: 4,
    },
    buttonContainer: {
      paddingHorizontal: 20,
      paddingBottom: 34,
      paddingTop: 20,
      gap: 12,
    },
    scanButton: {
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 20,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    scanButtonContent: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    scanButtonText: {
      color: "white",
      fontSize: 16,
      fontWeight: "600",
    },
    saveButton: {
      borderRadius: 12,
      paddingVertical: 16,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    saveButtonText: {
      color: "white",
      fontSize: 18,
      fontWeight: "600",
    },
    // Picker styles
    pickerOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "flex-end",
    },
    pickerContainer: {
      maxHeight: "80%",
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    pickerHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
    },
    pickerTitle: {
      fontSize: 18,
      fontWeight: "600",
      textAlign: "center",
    },
    pickerButton: {
      fontSize: 16,
      fontWeight: "500",
    },
    pickerScrollView: {
      maxHeight: 400,
    },
    pickerItem: {
      paddingHorizontal: 20,
      paddingVertical: 16,
    },
    pickerItemText: {
      fontSize: 16,
    },
    customModalContent: {
      padding: 20,
    },
    datePickerContainer: {
      width: "100%",
      marginHorizontal: 0,
    },
    datePicker: {
      width: "100%",
      height: 200,
    },
    // Loading overlay
    loadingOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 9999,
    },
    loadingContainer: {
      paddingHorizontal: 30,
      paddingVertical: 20,
      borderRadius: 12,
      alignItems: "center",
    },
    loadingText: {
      fontSize: 16,
      fontWeight: "600",
      marginBottom: 8,
      textAlign: "center",
    },
    loadingSubtext: {
      fontSize: 14,
      textAlign: "center",
      lineHeight: 20,
    },
    // AI Modal styles
    aiModalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "flex-end",
    },
    aiModalContainer: {
      width: "100%",
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      maxHeight: "85%",
      minHeight: "60%",
      paddingBottom: 20,
    },
    aiModalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingVertical: 16,
    },
    aiModalTitle: {
      fontSize: 18,
      fontWeight: "600",
      flex: 1,
      textAlign: "center",
    },
    aiModalSubtitle: {
      fontSize: 14,
      textAlign: "center",
      marginHorizontal: 20,
      marginTop: 10,
      marginBottom: 30,
    },
    aiModalContent: {
      flex: 1,
      paddingHorizontal: 20,
    },
    aiGrid: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 12,
    },
    aiGridOption: {
      flex: 1,
      alignItems: "center",
      padding: 16,
      borderRadius: 12,
      minHeight: 90,
      justifyContent: "center",
    },
    aiOptionIcon: {
      marginBottom: 8,
    },
    aiOptionTitle: {
      fontSize: 14,
      fontWeight: "600",
      marginBottom: 4,
      textAlign: "center",
    },
    aiOptionSubtitle: {
      fontSize: 12,
      textAlign: "center",
      lineHeight: 14,
    },
    // Statement Upload Modal Styles
    statementModalContainer: {
      flex: 1,
      paddingTop: 50,
    },
    statementModalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
    },
    headerBackButton: {
      width: 40,
      height: 40,
      justifyContent: "center",
      alignItems: "center",
    },
    statementModalTitle: {
      fontSize: 18,
      fontWeight: "600",
      flex: 1,
      textAlign: "center",
    },
    statementModalContent: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 20,
    },
    uploadArea: {
      borderWidth: 2,
      borderStyle: "dashed",
      borderRadius: 12,
      padding: 30,
      alignItems: "center",
      marginBottom: 20,
    },
    uploadIconContainer: {
      width: 60,
      height: 60,
      borderRadius: 30,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 10,
    },
    uploadTitle: {
      fontSize: 18,
      fontWeight: "600",
      marginTop: 10,
    },
    uploadSubtitle: {
      fontSize: 14,
      marginTop: 4,
      textAlign: "center",
    },
    quickOptionsContainer: {
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
    },
    quickOptionsTitle: {
      fontSize: 16,
      fontWeight: "600",
      marginBottom: 12,
    },
    fileTypesGrid: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    fileTypeItem: {
      alignItems: "center",
      flex: 1,
    },
    fileTypeIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 8,
    },
    fileTypeLabel: {
      fontSize: 12,
      fontWeight: "500",
    },
    tipsContainer: {
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
    },
    tipsHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
    },
    tipsTitle: {
      fontSize: 14,
      fontWeight: "600",
      marginLeft: 8,
    },
    tipsList: {
      marginLeft: 24,
    },
    tipItem: {
      fontSize: 12,
      lineHeight: 18,
      marginBottom: 2,
    },
  });
