import React from "react";
import {
  Home,
  Droplets,
  CreditCard,
  ShoppingCart,
  Car,
  Wifi,
  Utensils,
  Pizza,
  Laptop,
  Gift,
  HeartPulse,
  Wallet,
  Plane,
  GraduationCap,
  Coffee,
  DollarSign,
  Film,
  Music,
  Book,
  Shirt,
  Smartphone,
  Baby,
  Palette,
  Briefcase,
  Wrench,
  Building,
  Bus,
  Wind,
  Zap,
  Globe,
  LifeBuoy,
  Coins,
  PiggyBank
} from "lucide-react-native";

// Map of icon names to lucide icon components
export const iconMap: Record<string, React.ReactNode> = {
  Home: <Home size={16} />,
  Droplets: <Droplets size={16} />,
  CreditCard: <CreditCard size={16} />,
  ShoppingCart: <ShoppingCart size={16} />,
  Car: <Car size={16} />,
  Wifi: <Wifi size={16} />,
  Utensils: <Utensils size={16} />,
  Pizza: <Pizza size={16} />,
  Laptop: <Laptop size={16} />,
  Gift: <Gift size={16} />,
  HeartPulse: <HeartPulse size={16} />,
  Wallet: <Wallet size={16} />,
  Plane: <Plane size={16} />,
  GraduationCap: <GraduationCap size={16} />,
  Coffee: <Coffee size={16} />,
  Film: <Film size={16} />,
  Music: <Music size={16} />,
  Book: <Book size={16} />,
  Shirt: <Shirt size={16} />,
  Smartphone: <Smartphone size={16} />,
  Baby: <Baby size={16} />,
  Palette: <Palette size={16} />,
  Briefcase: <Briefcase size={16} />,
  Wrench: <Wrench size={16} />,
  Building: <Building size={16} />,
  Bus: <Bus size={16} />,
  Wind: <Wind size={16} />,
  Zap: <Zap size={16} />,
  Globe: <Globe size={16} />,
  LifeBuoy: <LifeBuoy size={16} />,
  Coins: <Coins size={16} />,
  PiggyBank: <PiggyBank size={16} />,
  DollarSign: <DollarSign size={16} />,
};

// Available icons for selection
export const availableIcons = [
  "Home", "Droplets", "CreditCard", "ShoppingCart", "Car", "Wifi", "Utensils",
  "Pizza", "Laptop", "Gift", "HeartPulse", "Wallet", "Plane", "GraduationCap", 
  "Coffee", "Film", "Music", "Book", "Shirt", "Smartphone", "Baby", "Palette", 
  "Briefcase", "Wrench", "Building", "Bus", "Wind", "Zap", "Globe", "LifeBuoy",
  "Coins", "PiggyBank", "DollarSign"
];
