import {
  Home,
  DollarSign,
  ShoppingCart,
  Car,
  Shield,
  Heart,
  User,
  BookOpen,
  Smartphone,
  Wifi,
  CreditCard,
  Receipt,
  Utensils,
  Film,
  ShoppingBag,
  Plane,
  Headphones,
  Gamepad,
  Activity,
  Scissors,
  TrendingUp,
  Umbrella,
  Baby,
  Briefcase,
  AlertTriangle,
  Calendar,
  Building,
  Coffee,
  Gift,
  Diamond,
  Bike,
  Edit3,
  Music,
  Zap,
  Truck,
  School,
  Globe,
} from "lucide-react-native";

export const categoryIcons: Record<string, React.ReactNode> = {
  // Housing & Utilities
  "Rent/Mortgage": <Home size={16} />,
  "Rent": <Home size={16} />,
  "Mortgage": <Home size={16} />,
  "Housing": <Home size={16} />,
  "Utilities": <DollarSign size={16} />,
  "Electric": <Zap size={16} />,
  "Water": <DollarSign size={16} />,
  "Gas": <DollarSign size={16} />,
  "Internet": <Wifi size={16} />,
  "Phone Bill": <Smartphone size={16} />,

  // Food & Dining
  "Groceries": <ShoppingCart size={16} />,
  "Dining Out": <Utensils size={16} />,
  "Restaurants": <Utensils size={16} />,
  "Food": <ShoppingCart size={16} />,
  "Coffee Shops": <Coffee size={16} />,

  // Transportation
  "Transportation": <Car size={16} />,
  "Gas/Fuel": <Car size={16} />,
  "Car Payment": <Car size={16} />,
  "Car Insurance": <Car size={16} />,
  "Car Maintenance": <Car size={16} />,
  "Public Transport": <Truck size={16} />,
  "Parking": <Car size={16} />,
  "Cycling": <Bike size={16} />,

  // Insurance & Financial
  "Insurance": <Shield size={16} />,
  "Health Insurance": <Shield size={16} />,
  "Life Insurance": <Shield size={16} />,
  "Home Insurance": <Shield size={16} />,
  "Debt Payments": <CreditCard size={16} />,
  "Loan EMI": <Receipt size={16} />,
  "Credit Card Payment": <CreditCard size={16} />,
  "Bank Fees": <Building size={16} />,

  // Health & Personal
  "Healthcare": <Heart size={16} />,
  "Medical": <Heart size={16} />,
  "Pharmacy": <Heart size={16} />,
  "Personal Care": <User size={16} />,
  "Beauty & Spa": <Scissors size={16} />,
  "Gym Membership": <Activity size={16} />,
  "Fitness": <Activity size={16} />,

  // Family & Education
  "Childcare": <User size={16} />,
  "Education (Tuition/Fees)": <BookOpen size={16} />,
  "Education": <BookOpen size={16} />,
  "School Supplies": <School size={16} />,
  "Books": <BookOpen size={16} />,
  "Babysitter": <Baby size={16} />,
  "Baby Supplies": <Baby size={16} />,

  // Shopping & Entertainment
  "Shopping": <ShoppingBag size={16} />,
  "Clothing": <ShoppingBag size={16} />,
  "Electronics": <Smartphone size={16} />,
  "Home Decor": <Home size={16} />,
  "Gifts & Celebrations": <Gift size={16} />,
  "Gifts": <Gift size={16} />,
  "Entertainment": <Film size={16} />,
  "Movies": <Film size={16} />,
  "Music": <Music size={16} />,
  "Hobbies": <Gamepad size={16} />,
  "Games": <Gamepad size={16} />,
  "Subscriptions (Netflix, Spotify)": <Headphones size={16} />,
  "Subscriptions": <Headphones size={16} />,

  // Travel & Vacation
  "Travel": <Plane size={16} />,
  "Vacation": <Umbrella size={16} />,
  "Airfare": <Plane size={16} />,
  "Hotels": <Building size={16} />,
  "Vacation Rental": <Home size={16} />,
  "Travel Insurance": <Shield size={16} />,

  // Savings & Investments
  "Emergency Fund": <AlertTriangle size={16} />,
  "Retirement": <Calendar size={16} />,
  "Investments (Stocks, Mutual Funds)": <TrendingUp size={16} />,
  "Investments": <TrendingUp size={16} />,
  "Stocks": <TrendingUp size={16} />,
  "Mutual Funds": <TrendingUp size={16} />,
  "Large Purchase (Car, House)": <DollarSign size={16} />,
  "Education Savings": <BookOpen size={16} />,
  "Vacation Savings": <Umbrella size={16} />,
  "Wedding Fund": <Heart size={16} />,
  "Baby Fund": <Baby size={16} />,
  "Side Hustle Savings": <Briefcase size={16} />,
  "Down Payment": <Home size={16} />,
  "Health Fund": <Heart size={16} />,
  "Debt Repayment Savings": <CreditCard size={16} />,

  // Income
  "Salary": <DollarSign size={16} />,
  "Bonus": <DollarSign size={16} />,
  "Interest": <DollarSign size={16} />,
  "Dividends": <TrendingUp size={16} />,
  "Rental Income": <Home size={16} />,
  "Freelance": <Edit3 size={16} />,
  "Side Hustle": <Briefcase size={16} />,

  // Luxury & Miscellaneous
  "Luxury Items": <Diamond size={16} />,
  "International": <Globe size={16} />,
  "Loan Disbursement": <CreditCard size={16} />,
  "Loan Collection": <Receipt size={16} />,
  "Debt Repayment": <CreditCard size={16} />,
  "Debt Collection": <Receipt size={16} />,
};
