import React from "react";
import {
  // Food & Dining
  Utensils,
  Coffee,
  Pizza,
  ChefHat,
  Wine,
  IceCream,
  Apple,
  ShoppingCart,

  // Transportation
  Car,
  Fuel,
  Bus,
  Train,
  Plane,
  Bike,

  // Shopping & Personal
  ShoppingBag,
  Shirt,
  Scissors,
  Heart,
  Palette,
  Gift,

  // Entertainment
  Film,
  Music,
  Gamepad,
  Book,
  Camera,
  Headphones,

  // Health & Fitness
  Activity,
  Dumbbell,
  Stethoscope,
  Pill,

  // Home & Utilities
  Home,
  Zap,
  Droplets,
  Wifi,
  Smartphone,
  Tv,

  // Financial
  CreditCard,
  DollarSign,
  PiggyBank,
  TrendingUp,
  Building,
  Banknote,
  Coins,
  Receipt,
  Shield,
  Target,
  Percent,

  // Education & Work
  GraduationCap,
  BookOpen,
  Briefcase,
  Laptop,
  Users,
  FileText,
  Award,
  Lightbulb,

  // Travel
  MapPin,
  Luggage,
  Hotel,
  Globe,
  Navigation,

  // Additional icons for new subcategories
  Baby,
  PawPrint,
  Wrench,
  Calendar,
  Star,
  Crown,
  Sparkles,
  Gem,
  Package,
  Truck,
  RefreshCw,
  ArrowUpRight,
  ArrowDownLeft,
  Clock,
  User,
  Users2,
  Handshake,
  Megaphone,
  Paintbrush,
  Hammer,
  Umbrella,
  TreePine,
  Mountain,
  Sun,
  Moon,
  Flower,
  Leaf,
  Waves,
  Flame,
  Snowflake,
  CloudRain,
  Thermometer,
  Wind,
  Eye,
  Ear,
  Hand,
  Footprints,
  MessageCircle,
  Mail,
  Phone,
  Video,
  Mic,
  Speaker,
  Volume2,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Repeat,
  Shuffle,
  Download,
  Upload,
  Share,
  Link,
  Search,
  Filter,
  Settings,
  Cog,
  Lock,
  Unlock,
  Key,
  ShieldCheck,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Info,
  HelpCircle,
  Plus,
  Minus,
  X,
  Check,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  RotateCcw,
  RotateCw,
  Maximize,
  Minimize,
  Move,
  Copy,
  Clipboard,
  Edit,
  Trash,
  Archive,
  Folder,
  File,
  Image,
  FileImage,
  FileVideo,
  FileAudio,
  FileSpreadsheet,
  Database,
  Server,
  HardDrive,
  Cpu,
  Monitor,
  Keyboard,
  Mouse,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Spade,
  Club,
  Diamond,
  HeartHandshake,
  Smile,
  Frown,
  Meh,
  Angry,
  Laugh,
  Battery,
  BatteryLow,
  Plug,
  Power,
  PowerOff,
  Bluetooth,
  Usb,
  MemoryStick,
  Disc,
  Radio,
  Satellite,
  Radar,
  Compass,
  Map,
  Route,
  Signpost,
  Milestone,
  Flag,
  Bookmark,
  Tag,
  Hash,
  AtSign,
  Euro,
  PoundSterling,
  IndianRupee,
  Bitcoin,
  Wallet,
  Landmark,
  University,
  School,
  Library,
  Church,
  Castle,
  Factory,
  Warehouse,
  Store,
  Tent,
  Caravan,
  Sailboat,
  Ship,
  Rocket,
  Ghost,
  Skull,
  Bone,
  Feather,
  Egg,
  Sprout,
  TreeDeciduous,
  Clover,
  Cherry,
  Grape,
  Banana,
  Carrot,
  Milk,
  Croissant,
  Cookie,
  Cake,
  Sandwich,
  Popcorn,
} from "lucide-react-native";

/**
 * Mapping from subcategory names to Lucide icon names (for database storage)
 */
export const subcategoryToIconName: Record<string, string> = {
  // Food & Dining
  food: "Utensils",
  groceries: "ShoppingCart",
  restaurants: "Utensils",
  "dining out": "Utensils",
  "fast food": "Pizza",
  coffee: "Coffee",
  "coffee shops": "Coffee",
  alcohol: "Wine",
  snacks: "IceCream",
  desserts: "IceCream",
  fruits: "Apple",
  vegetables: "Apple",
  cooking: "ChefHat",

  // Transportation
  gas: "Fuel",
  fuel: "Fuel",
  "car payment": "Car",
  "car maintenance": "Wrench",
  "car insurance": "Car",
  "public transport": "Bus",
  bus: "Bus",
  train: "Train",
  subway: "Train",
  taxi: "Car",
  uber: "Car",
  lyft: "Car",
  parking: "Car",
  tolls: "Car",
  cycling: "Bike",
  bike: "Bike",

  // Shopping & Personal Care
  clothing: "Shirt",
  shoes: "Shirt",
  "personal care": "Scissors",
  haircut: "Scissors",
  beauty: "Palette",
  cosmetics: "Palette",
  spa: "Heart",
  gifts: "Gift",
  electronics: "Smartphone",
  gadgets: "Smartphone",

  // Entertainment & Recreation
  movies: "Film",
  cinema: "Film",
  music: "Music",
  concerts: "Music",
  streaming: "Headphones",
  netflix: "Tv",
  spotify: "Music",
  games: "Gamepad",
  gaming: "Gamepad",
  books: "Book",
  reading: "BookOpen",
  hobbies: "Camera",
  photography: "Camera",

  // Health & Fitness
  gym: "Activity",
  fitness: "Dumbbell",
  workout: "Dumbbell",
  medical: "Stethoscope",
  doctor: "Stethoscope",
  hospital: "Stethoscope",
  pharmacy: "Pill",
  medicine: "Pill",
  dental: "Stethoscope",
  therapy: "Heart",

  // Home & Utilities
  rent: "Home",
  mortgage: "Home",
  electricity: "Zap",
  water: "Droplets",
  internet: "Wifi",
  phone: "Smartphone",
  cable: "Tv",
  "home maintenance": "Wrench",
  repairs: "Wrench",

  // Financial & Insurance
  "bank fees": "Building",
  "credit card": "CreditCard",
  "loan payment": "DollarSign",
  insurance: "Building",
  investments: "TrendingUp",
  savings: "PiggyBank",
  retirement: "PiggyBank",

  // Education & Work
  tuition: "GraduationCap",
  education: "BookOpen",
  "school supplies": "BookOpen",
  "work expenses": "Briefcase",
  "office supplies": "Laptop",

  // Travel & Vacation
  flights: "Plane",
  hotels: "Hotel",
  accommodation: "Hotel",
  travel: "MapPin",
  vacation: "Luggage",

  // Family & Pets
  childcare: "Baby",
  "baby supplies": "Baby",
  "pet care": "PawPrint",
  veterinary: "PawPrint",
  "pet food": "PawPrint",

  // Miscellaneous
  subscriptions: "Calendar",
  donations: "Heart",
  charity: "Heart",
  taxes: "Building",
  legal: "Building",

  // New subcategories from database
  "app/software revenue": "Laptop",
  "software revenue": "Laptop",
  "baby fund": "Baby",
  "beauty & spa": "Sparkles",
  "beauty and spa": "Sparkles",
  bonuses: "Star",
  "business revenue": "Briefcase",
  "capital gains": "TrendingUp",
  "cashback & rewards": "Percent",
  "cashback and rewards": "Percent",
  "child support": "Baby",
  commission: "Handshake",
  "competition prizes": "Award",
  "content creation": "Camera",
  "contract work": "FileText",
  "crafts & handmade": "Paintbrush",
  "crafts and handmade": "Paintbrush",
  "debt payments": "CreditCard",
  "debt repayment savings": "PiggyBank",
  "disability benefits": "Shield",
  "dividend income": "TrendingUp",
  "down payment": "Home",
  "education (tuition/fees)": "GraduationCap",
  "education tuition fees": "GraduationCap",
  "emergency fund": "Shield",
  entertainment: "Film",
  "freelance/consulting": "Lightbulb",
  "freelance consulting": "Lightbulb",
  "gifts & cash": "Gift",
  "gifts and cash": "Gift",
  "gifts & celebrations": "Gift",
  "gifts and celebrations": "Gift",
  "gig economy": "Truck",
  "gym membership": "Dumbbell",
  healthcare: "Stethoscope",
  "health fund": "Heart",
  "home decor": "Home",
  housing: "Home",
  inheritance: "Crown",
  "insurance payouts": "Shield",
  "insurance reimbursements": "Shield",
  "interest income": "Percent",
  "investments (stocks, mutual funds)": "TrendingUp",
  "investments stocks mutual funds": "TrendingUp",
  "large purchase (car, house)": "Home",
  "large purchase car house": "Home",
  "loan emi": "CreditCard",
  "lottery/gambling": "Dice1",
  "lottery gambling": "Dice1",
  "luxury items": "Gem",
  "medical reimbursements": "Stethoscope",
  "overtime pay": "Clock",
  "p2p lending returns": "Handshake",
  pension: "PiggyBank",
  "phone bill": "Smartphone",
  "product returns": "RefreshCw",
  "reit distributions": "Building",
  "rental income": "Home",
  "rent/mortgage": "Home",
  reselling: "Package",
  royalties: "Crown",
  "salary/wages": "User",
  "salary wages": "User",
  shopping: "ShoppingBag",
  "side hustle savings": "PiggyBank",
  "social security": "Shield",
  "subscriptions (netflix, spotify)": "Tv",
  "subscriptions netflix spotify": "Tv",
  subsidies: "Handshake",
  "tax refunds": "Building",
  "teaching/tutoring": "GraduationCap",
  "teaching tutoring": "GraduationCap",
  "tips & gratuities": "Hand",
  "tips and gratuities": "Hand",
  transportation: "Car",
  "travel refunds": "Plane",
  "unemployment benefits": "Shield",
  utilities: "Zap",
  "utility refunds": "Zap",
  "vacation savings": "Luggage",
  "wedding fund": "Heart",
  "work reimbursements": "Briefcase",
};

/**
 * Get Lucide icon name for a subcategory (for database storage)
 */
export const getSubcategoryIconName = (
  subcategoryName?: string | null
): string => {
  if (!subcategoryName) return "Receipt";

  const normalizedName = subcategoryName.toLowerCase().trim();
  return subcategoryToIconName[normalizedName] || "Receipt";
};

/**
 * Comprehensive subcategory icon mapping
 * Maps subcategory names to Lucide React Native icons
 */
export const subcategoryIconMap: Record<string, React.ReactNode> = {
  // Food & Dining Subcategories
  food: <Utensils size={16} color="#10B981" />,
  groceries: <ShoppingCart size={16} color="#10B981" />,
  restaurants: <Utensils size={16} color="#EF4444" />,
  "dining out": <Utensils size={16} color="#EF4444" />,
  "fast food": <Pizza size={16} color="#EF4444" />,
  coffee: <Coffee size={16} color="#8B5CF6" />,
  "coffee shops": <Coffee size={20} color="#8B5CF6" />,
  alcohol: <Wine size={20} color="#DC2626" />,
  snacks: <IceCream size={20} color="#F59E0B" />,
  desserts: <IceCream size={20} color="#F59E0B" />,
  fruits: <Apple size={20} color="#10B981" />,
  vegetables: <Apple size={20} color="#10B981" />,
  cooking: <ChefHat size={20} color="#F59E0B" />,

  // Transportation Subcategories
  gas: <Fuel size={20} color="#EF4444" />,
  fuel: <Fuel size={20} color="#EF4444" />,
  "car payment": <Car size={20} color="#3B82F6" />,
  "car maintenance": <Wrench size={20} color="#6B7280" />,
  "car insurance": <Car size={20} color="#8B5CF6" />,
  "public transport": <Bus size={20} color="#10B981" />,
  bus: <Bus size={20} color="#10B981" />,
  train: <Train size={20} color="#10B981" />,
  subway: <Train size={20} color="#10B981" />,
  taxi: <Car size={20} color="#F59E0B" />,
  uber: <Car size={20} color="#1F2937" />,
  lyft: <Car size={20} color="#EC4899" />,
  parking: <Car size={20} color="#6B7280" />,
  tolls: <Car size={20} color="#6B7280" />,
  cycling: <Bike size={20} color="#10B981" />,
  bike: <Bike size={20} color="#10B981" />,

  // Shopping & Personal Care
  clothing: <Shirt size={20} color="#8B5CF6" />,
  shoes: <Shirt size={20} color="#8B5CF6" />,
  "personal care": <Scissors size={20} color="#EC4899" />,
  haircut: <Scissors size={20} color="#EC4899" />,
  beauty: <Palette size={20} color="#EC4899" />,
  cosmetics: <Palette size={20} color="#EC4899" />,
  spa: <Heart size={20} color="#EC4899" />,
  gifts: <Gift size={20} color="#F59E0B" />,
  electronics: <Smartphone size={20} color="#3B82F6" />,
  gadgets: <Smartphone size={20} color="#3B82F6" />,

  // Entertainment & Recreation
  movies: <Film size={20} color="#8B5CF6" />,
  cinema: <Film size={20} color="#8B5CF6" />,
  music: <Music size={20} color="#10B981" />,
  concerts: <Music size={20} color="#10B981" />,
  streaming: <Headphones size={20} color="#EF4444" />,
  netflix: <Tv size={20} color="#DC2626" />,
  spotify: <Music size={20} color="#10B981" />,
  games: <Gamepad size={20} color="#3B82F6" />,
  gaming: <Gamepad size={20} color="#3B82F6" />,
  books: <Book size={20} color="#8B5CF6" />,
  reading: <BookOpen size={20} color="#8B5CF6" />,
  hobbies: <Camera size={20} color="#F59E0B" />,
  photography: <Camera size={20} color="#F59E0B" />,

  // Health & Fitness
  gym: <Activity size={20} color="#EF4444" />,
  fitness: <Dumbbell size={20} color="#EF4444" />,
  workout: <Dumbbell size={20} color="#EF4444" />,
  medical: <Stethoscope size={20} color="#DC2626" />,
  doctor: <Stethoscope size={20} color="#DC2626" />,
  hospital: <Stethoscope size={20} color="#DC2626" />,
  pharmacy: <Pill size={20} color="#10B981" />,
  medicine: <Pill size={20} color="#10B981" />,
  dental: <Stethoscope size={20} color="#3B82F6" />,
  therapy: <Heart size={20} color="#EC4899" />,

  // Home & Utilities
  rent: <Home size={20} color="#3B82F6" />,
  mortgage: <Home size={20} color="#3B82F6" />,
  electricity: <Zap size={20} color="#F59E0B" />,
  water: <Droplets size={20} color="#3B82F6" />,
  internet: <Wifi size={20} color="#8B5CF6" />,
  phone: <Smartphone size={20} color="#6B7280" />,
  cable: <Tv size={20} color="#6B7280" />,
  "home maintenance": <Wrench size={20} color="#6B7280" />,
  repairs: <Wrench size={20} color="#6B7280" />,

  // Financial & Insurance
  "bank fees": <Building size={20} color="#6B7280" />,
  "credit card": <CreditCard size={20} color="#EF4444" />,
  "loan payment": <DollarSign size={20} color="#EF4444" />,
  insurance: <Building size={20} color="#3B82F6" />,
  investments: <TrendingUp size={20} color="#10B981" />,
  savings: <PiggyBank size={20} color="#10B981" />,
  retirement: <PiggyBank size={20} color="#3B82F6" />,

  // Education & Work
  tuition: <GraduationCap size={20} color="#8B5CF6" />,
  education: <BookOpen size={20} color="#8B5CF6" />,
  "school supplies": <BookOpen size={20} color="#F59E0B" />,
  "work expenses": <Briefcase size={20} color="#6B7280" />,
  "office supplies": <Laptop size={20} color="#6B7280" />,

  // Travel & Vacation
  flights: <Plane size={20} color="#3B82F6" />,
  hotels: <Hotel size={20} color="#8B5CF6" />,
  accommodation: <Hotel size={20} color="#8B5CF6" />,
  travel: <MapPin size={20} color="#10B981" />,
  vacation: <Luggage size={20} color="#F59E0B" />,

  // Family & Pets
  childcare: <Baby size={20} color="#EC4899" />,
  "baby supplies": <Baby size={20} color="#EC4899" />,
  "pet care": <PawPrint size={20} color="#8B5CF6" />,
  veterinary: <PawPrint size={20} color="#DC2626" />,
  "pet food": <PawPrint size={20} color="#10B981" />,

  // Miscellaneous
  subscriptions: <Calendar size={20} color="#6B7280" />,
  donations: <Heart size={20} color="#DC2626" />,
  charity: <Heart size={20} color="#DC2626" />,
  taxes: <Building size={20} color="#6B7280" />,
  legal: <Building size={20} color="#6B7280" />,
};

/**
 * Render Lucide icon from icon name (from database)
 */
export const renderIconFromName = (
  iconName: string,
  size: number = 16,
  color: string = "#10B981"
): React.ReactNode | null => {
  // Map of icon names to components
  const iconComponents: Record<string, any> = {
    Utensils,
    Coffee,
    Pizza,
    ChefHat,
    Wine,
    IceCream,
    Apple,
    ShoppingCart,
    Car,
    Fuel,
    Bus,
    Train,
    Plane,
    Bike,
    ShoppingBag,
    Shirt,
    Scissors,
    Heart,
    Palette,
    Gift,
    Film,
    Music,
    Gamepad,
    Book,
    Camera,
    Headphones,
    Activity,
    Dumbbell,
    Stethoscope,
    Pill,
    Home,
    Zap,
    Droplets,
    Wifi,
    Smartphone,
    Tv,
    CreditCard,
    DollarSign,
    PiggyBank,
    TrendingUp,
    Building,
    Banknote,
    Coins,
    Receipt,
    Shield,
    Target,
    Percent,
    GraduationCap,
    BookOpen,
    Briefcase,
    Laptop,
    Users,
    FileText,
    Award,
    Lightbulb,
    MapPin,
    Luggage,
    Hotel,
    Globe,
    Navigation,
    Baby,
    PawPrint,
    Wrench,
    Calendar,
    Star,
    Crown,
    Sparkles,
    Gem,
    Package,
    Truck,
    RefreshCw,
    ArrowUpRight,
    ArrowDownLeft,
    Clock,
    User,
    Users2,
    Handshake,
    Megaphone,
    Paintbrush,
    Hammer,
    Umbrella,
    TreePine,
    Mountain,
    Sun,
    Moon,
    Flower,
    Leaf,
    Waves,
    Flame,
    Snowflake,
    CloudRain,
    Thermometer,
    Wind,
    Eye,
    Ear,
    Hand,
    Footprints,
    MessageCircle,
    Mail,
    Phone,
    Video,
    Mic,
    Speaker,
    Volume2,
    Play,
    Pause,
    SkipForward,
    SkipBack,
    Repeat,
    Shuffle,
    Download,
    Upload,
    Share,
    Link,
    Search,
    Filter,
    Settings,
    Cog,
    Lock,
    Unlock,
    Key,
    ShieldCheck,
    AlertTriangle,
    CheckCircle,
    XCircle,
    Info,
    HelpCircle,
    Plus,
    Minus,
    X,
    Check,
    ChevronUp,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    RotateCcw,
    RotateCw,
    Maximize,
    Minimize,
    Move,
    Copy,
    Clipboard,
    Edit,
    Trash,
    Archive,
    Folder,
    File,
    Image,
    FileImage,
    FileVideo,
    FileAudio,
    FileSpreadsheet,
    Database,
    Server,
    HardDrive,
    Cpu,
    Monitor,
    Keyboard,
    Mouse,
    Printer,
    Webcam,
    Gamepad2,
    Joystick,
    Dice1,
    Dice2,
    Dice3,
    Dice4,
    Dice5,
    Dice6,
    Spade,
    Club,
    Diamond,
    HeartHandshake,
    Smile,
    Frown,
    Meh,
    Angry,
    Laugh,
    Battery,
    BatteryLow,
    Plug,
    Power,
    PowerOff,
    Bluetooth,
    Usb,
    MemoryStick,
    Disc,
    Radio,
    Satellite,
    Radar,
    Compass,
    Map,
    Route,
    Signpost,
    Milestone,
    Flag,
    Bookmark,
    Tag,
    Hash,
    AtSign,
    Euro,
    PoundSterling,
    IndianRupee,
    Bitcoin,
    Wallet,
    Landmark,
    University,
    School,
    Library,
    Church,
    Castle,
    Factory,
    Warehouse,
    Store,
    Tent,
    Caravan,
    Sailboat,
    Ship,
    Rocket,
    Ghost,
    Skull,
    Bone,
    Feather,
    Egg,
    Sprout,
    TreeDeciduous,
    Clover,
    Cherry,
    Grape,
    Banana,
    Carrot,
    Milk,
    Croissant,
    Cookie,
    Cake,
    Sandwich,
    Popcorn,
  };

  const IconComponent = iconComponents[iconName];
  if (!IconComponent) {
    // Fallback to Receipt icon if icon name not found
    return <Receipt size={size} color={color} />;
  }

  return <IconComponent size={size} color={color} />;
};

/**
 * Get icon for subcategory using database icon name or fallback to name-based lookup
 */
export const getSubcategoryIconFromDB = (
  dbIconName?: string | null,
  subcategoryName?: string | null,
  size: number = 16,
  color: string = "#10B981"
): React.ReactNode | null => {
  // First try to use the database icon name
  if (dbIconName && dbIconName !== "Receipt" && dbIconName !== "📄") {
    return renderIconFromName(dbIconName, size, color);
  }

  // Fallback to name-based lookup
  if (subcategoryName) {
    const iconName = getSubcategoryIconName(subcategoryName);
    return renderIconFromName(iconName, size, color);
  }

  return null;
};

/**
 * Get all available subcategory icon names
 */
export const getAvailableSubcategoryIcons = (): string[] => {
  return Object.keys(subcategoryIconMap);
};
